import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { BeatLoader } from "react-spinners";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider  session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Suspense fallback={<BeatLoader/>}>
            {children}
          </Suspense>
        </body>
      </html>
    </SessionProvider>
  );
}
